import jsPDF from "jspdf";

const money = new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
});

const formatMoney = (value) => money.format(Number(value || 0));
const formatDate = (value) =>
    value ? new Date(value).toLocaleDateString() : "-";

export const downloadPayslipPdf = ({
    payroll,
    salary,
    employeeName,
    hrName,
}) => {
    if (!payroll) return;

    const baseSalary = salary
        ? Number(salary.basic || 0) +
          Number(salary.hra || 0) +
          Number(salary.allowances || 0)
        : Number(payroll.grossSalary || 0);

    const overtimeRate =
        payroll.overtimeRate || salary?.overtimeRate || 0;
    const overtimeAmount =
        (payroll.overtimeHours || 0) * overtimeRate;
    const paidLeaveRate = salary?.paidLeaveDeduction || 0;
    const paidLeaveDeduction =
        payroll.paidLeaveDeduction ??
        (payroll.paidLeaveDays || 0) * paidLeaveRate;
    const halfDayRate = salary?.halfDayDeduction || 0;
    const halfDayDeduction =
        payroll.halfDayDeduction ??
        (payroll.halfDayLeaves || 0) * halfDayRate;
    const pfDeduction = Number(salary?.deductions?.pf || 0);
    const taxDeduction = Number(salary?.deductions?.tax || 0);

    const grossSalary =
        payroll.grossSalary ??
        baseSalary + overtimeAmount;
    const totalDeductions =
        payroll.deductions ??
        pfDeduction +
            taxDeduction +
            Number(paidLeaveDeduction || 0) +
            Number(halfDayDeduction || 0);
    const netPay = payroll.netPay ?? grossSalary - totalDeductions;

    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const marginX = 48;
    let cursorY = 56;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("Salary Payslip", marginX, cursorY);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Month: ${payroll.month || "-"}`, marginX, cursorY + 16);
    doc.text(
        `Status: ${payroll.paymentStatus || "-"}`,
        marginX + 220,
        cursorY + 16,
    );

    cursorY += 42;
    doc.setDrawColor(229, 231, 235);
    doc.line(marginX, cursorY, 547, cursorY);
    cursorY += 18;

    doc.setFont("helvetica", "bold");
    doc.text("Employee", marginX, cursorY);
    doc.setFont("helvetica", "normal");
    doc.text(employeeName || "Employee", marginX + 90, cursorY);
    cursorY += 16;
    doc.setFont("helvetica", "bold");
    doc.text("Processed By", marginX, cursorY);
    doc.setFont("helvetica", "normal");
    doc.text(hrName || "HR Team", marginX + 90, cursorY);
    cursorY += 16;
    doc.setFont("helvetica", "bold");
    doc.text("Paid On", marginX, cursorY);
    doc.setFont("helvetica", "normal");
    doc.text(formatDate(payroll.paidOn), marginX + 90, cursorY);

    cursorY += 28;
    doc.setDrawColor(229, 231, 235);
    doc.line(marginX, cursorY, 547, cursorY);
    cursorY += 22;

    doc.setFont("helvetica", "bold");
    doc.text("Earnings", marginX, cursorY);
    doc.text("Deductions", marginX + 260, cursorY);
    cursorY += 16;

    const rows = [
        ["Basic", formatMoney(salary?.basic)],
        ["HRA", formatMoney(salary?.hra)],
        ["Allowances", formatMoney(salary?.allowances)],
        ["Overtime", formatMoney(overtimeAmount)],
    ];

    const deductions = [
        ["PF", formatMoney(pfDeduction)],
        ["Tax", formatMoney(taxDeduction)],
        ["Paid Leave", formatMoney(paidLeaveDeduction)],
        ["Half Day", formatMoney(halfDayDeduction)],
    ];

    doc.setFont("helvetica", "normal");
    const startY = cursorY;
    rows.forEach(([label, value], idx) => {
        const y = startY + idx * 16;
        doc.text(label, marginX, y);
        doc.text(value, marginX + 140, y, { align: "right" });
    });
    deductions.forEach(([label, value], idx) => {
        const y = startY + idx * 16;
        doc.text(label, marginX + 260, y);
        doc.text(value, marginX + 440, y, { align: "right" });
    });

    cursorY = startY + 88;
    doc.setDrawColor(229, 231, 235);
    doc.line(marginX, cursorY, 547, cursorY);
    cursorY += 18;

    doc.setFont("helvetica", "bold");
    doc.text("Gross Salary", marginX, cursorY);
    doc.text(formatMoney(grossSalary), marginX + 160, cursorY, {
        align: "right",
    });
    doc.text("Total Deductions", marginX + 260, cursorY);
    doc.text(formatMoney(totalDeductions), marginX + 440, cursorY, {
        align: "right",
    });
    cursorY += 18;
    doc.setFontSize(12);
    doc.text("Net Pay", marginX, cursorY);
    doc.text(formatMoney(netPay), marginX + 160, cursorY, {
        align: "right",
    });

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by HRMS", marginX, 780);

    doc.save(`payslip-${payroll.month || "current"}.pdf`);
};
