const money = new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
});

const formatMoney = (value) => money.format(Number(value || 0));
const formatDate = (value) =>
    value ? new Date(value).toLocaleDateString() : "-";

export const openPayslip = ({
    payroll,
    salary,
    employeeName,
    hrName,
}) => {
    if (!payroll) return;

    const baseSalary = salary
        ? Number(salary.basic || 0) +
          Number(salary.hra || 0) +
          Number(salary.allowances || 0)
        : Number(payroll.grossSalary || 0);

    const overtimeRate =
        payroll.overtimeRate || salary?.overtimeRate || 0;
    const overtimeAmount =
        (payroll.overtimeHours || 0) * overtimeRate;
    const paidLeaveRate = salary?.paidLeaveDeduction || 0;
    const paidLeaveDeduction =
        payroll.paidLeaveDeduction ??
        (payroll.paidLeaveDays || 0) * paidLeaveRate;
    const halfDayRate = salary?.halfDayDeduction || 0;
    const halfDayDeduction =
        payroll.halfDayDeduction ??
        (payroll.halfDayLeaves || 0) * halfDayRate;

    const grossSalary =
        payroll.grossSalary ??
        baseSalary + overtimeAmount;
    const pfDeduction = Number(salary?.deductions?.pf || 0);
    const taxDeduction = Number(salary?.deductions?.tax || 0);
    const totalDeductions =
        payroll.deductions ??
        pfDeduction +
            taxDeduction +
            Number(paidLeaveDeduction || 0) +
            Number(halfDayDeduction || 0);
    const netPay = payroll.netPay ?? grossSalary - totalDeductions;

    const win = window.open("", "_blank", "width=900,height=700");
    if (!win) return;

    win.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Payslip</title>
<style>
    body { font-family: Arial, sans-serif; color: #111827; padding: 24px; }
    .header { display: flex; justify-content: space-between; align-items: center; }
    .title { font-size: 20px; font-weight: 700; }
    .muted { color: #6b7280; font-size: 12px; }
    .card { border: 1px solid #e5e7eb; border-radius: 12px; padding: 16px; margin-top: 16px; }
    .row { display: flex; justify-content: space-between; padding: 6px 0; }
    .row strong { font-weight: 600; }
    .total { font-size: 16px; font-weight: 700; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
    .tag { display: inline-block; padding: 4px 8px; border-radius: 999px; font-size: 12px; }
    .paid { background: #dcfce7; color: #166534; }
    .pending { background: #fef3c7; color: #92400e; }
</style>
</head>
<body>
    <div class="header">
        <div>
            <div class="title">Payslip</div>
            <div class="muted">Month: ${payroll.month || "-"}</div>
        </div>
        <div>
            <span class="tag ${
                payroll.paymentStatus === "Paid" ? "paid" : "pending"
            }">
                ${payroll.paymentStatus}
            </span>
        </div>
    </div>

    <div class="card">
        <div class="row"><strong>Employee</strong><span>${employeeName}</span></div>
        <div class="row"><strong>Processed By</strong><span>${hrName}</span></div>
        <div class="row"><strong>Paid On</strong><span>${formatDate(payroll.paidOn)}</span></div>
    </div>

    <div class="grid">
        <div class="card">
            <div class="row"><strong>Base Salary</strong><span>${formatMoney(baseSalary)}</span></div>
            <div class="row"><strong>Overtime</strong><span>${formatMoney(overtimeAmount)}</span></div>
            <div class="row total"><strong>Gross Salary</strong><span>${formatMoney(grossSalary)}</span></div>
        </div>
        <div class="card">
            <div class="row"><strong>PF Deduction</strong><span>${formatMoney(pfDeduction)}</span></div>
            <div class="row"><strong>Tax Deduction</strong><span>${formatMoney(taxDeduction)}</span></div>
            <div class="row"><strong>Paid Leave Deduction</strong><span>${formatMoney(paidLeaveDeduction)}</span></div>
            <div class="row"><strong>Half Day Deduction</strong><span>${formatMoney(halfDayDeduction)}</span></div>
            <div class="row total"><strong>Total Deductions</strong><span>${formatMoney(totalDeductions)}</span></div>
            <div class="row total"><strong>Receivable</strong><span>${formatMoney(netPay)}</span></div>
        </div>
    </div>

    <div class="card">
        <div class="row"><strong>Payment Status</strong><span>${payroll.paymentStatus}</span></div>
        <div class="row"><strong>Notes</strong><span>Generated by HRMS</span></div>
    </div>
</body>
</html>`);

    win.document.close();
    win.focus();
    win.onload = () => {
        win.print();
    };
};
